package algorithms;

/**
 * Created by chaozeyi on 18/1/11.
 */

/**
 * Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class problem_389 {

    public char findTheDifference(String s, String t) {
        int count1 = 0;
        int count2 = 0;
        for(int i = 0; i < s.length(); i++){
            count1 += s.charAt(i);
        }
        for(int i = 0; i < t.length(); i++){
            count2 += t.charAt(i);
        }
        char result = (char)Math.abs(count1-count2);
        return result;
    }

}
